### ISSUE TITLE
v0.39.0.0: Failed to check ruleset; file not found

### ISSUE THREAD

**Issue by syphernl** [terraform-linters/tflint-bundle#37] opened 2022-07-28 06:32 UTC
Today all of our Terraform pipelines started failing on `tflint` ([v0.39.0.0](https://github.com/orgs/terraform-linters/packages/container/tflint-bundle/29970418?tag=v0.39.0.0)):

I was able to reproduce this locally by running the following:

```shell
❯ docker run --rm -v $(pwd):/data -t ghcr.io/terraform-linters/tflint-bundle

Unable to find image 'ghcr.io/terraform-linters/tflint-bundle:latest' locally
latest: Pulling from terraform-linters/tflint-bundle
530afca65e2e: Already exists 
a70a19e69755: Pull complete 
8f9b3e47c202: Pull complete 
82a17f85f628: Pull complete 
3f6d410d8bd8: Pull complete 
Digest: sha256:e32e4adae6f0d37e942d12523b785f46bd2f20d3ddb44ef193d180908903dfac
Status: Downloaded newer image for ghcr.io/terraform-linters/tflint-bundle:latest
Failed to check ruleset; file not found
```

The previous version ([v0.38.1.0](https://github.com/terraform-linters/tflint-bundle/releases/tag/v0.38.1.0)) works fine:

```shell
❯ docker run --rm -v $(pwd):/data -t ghcr.io/terraform-linters/tflint-bundle:v0.38.1.0
Unable to find image 'ghcr.io/terraform-linters/tflint-bundle:v0.38.1.0' locally
v0.38.1.0: Pulling from terraform-linters/tflint-bundle
2408cc74d12b: Already exists 
f0290673f905: Pull complete 
7b95f59d4b4e: Pull complete 
9b4aa5dc042c: Pull complete 
1b85d805286a: Pull complete 
Digest: sha256:8aa1d7939bcf70ad76c577a8fb9fc4bd21b75ecc195807f613c5b0bb7bbbec7b
Status: Downloaded newer image for ghcr.io/terraform-linters/tflint-bundle:v0.38.1.0
Failed to check ruleset; no valid credential sources for tflint-ruleset-aws found.

Please see https://github.com/terraform-linters/tflint-ruleset-aws/blob/master/docs/deep_checking.md
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: no route to host
```

(the error is expected as I did not authenticate against AWS)

**Comment by wata727** [comment] 2022-07-29 13:06
Thank you for reporting this. More detailed information is needed to resolve the issue.

- Does this issue occur even if you have TFLint installed locally? Or is it a tflint-bundle specific issue?
- Is there a minimum code or reproduction step to reproduce the issue?

**Comment by syphernl** [comment] 2022-08-01 05:31
With local `tflint` it is failing with a different error:

```shell
❯ flint
❯ tflint --version
TFLint version 0.39.0
❯ tflint .
Failed to initialize plugins; Plugin `aws` not found in /home/username/.tflint.d/plugins
```

The entire `.tflint.d` directory does not exist. I've tried creating it and using `tflint --init` but neither of this worked either.

The `.tflint.hcl` we use is:

```hcl
config {
  module = true
  force = false
}

plugin "aws" {
  enabled = true
  deep_check = true
}

rule "terraform_comment_syntax" {
  enabled = true
}

rule "terraform_documented_outputs" {
  enabled = true
}

rule "terraform_documented_variables" {
  enabled = true
}

rule "terraform_typed_variables" {
  enabled = true
}

rule "terraform_naming_convention" {
  enabled = true
}

rule "terraform_required_version" {
  enabled = true
}

rule "terraform_required_providers" {
  enabled = true
}

rule "terraform_deprecated_index" {
  enabled = true
}
```

**Comment by syphernl** [comment] 2022-08-03 06:31
With `deep_check = false` in the `aws` plugin config it is not giving this error.

**Comment by bendrucker** [comment] 2022-08-03 15:24
Duplicate of https://github.com/terraform-linters/tflint/issues/1465

**Closed by bendrucker** 2022-08-03 15:24 UTC
